CREATE TABLE USER_1
(
  ID         BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255),
  LAST_NAME  VARCHAR(255),
  E_MAIL     VARCHAR(255)           NOT NULL,
  STREET     VARCHAR(255)           NOT NULL,
  ZIP_CODE   VARCHAR(255)           NOT NULL,
  CITY       VARCHAR(255)           NOT NULL
);

CREATE TABLE USER_2
(
  ID               BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  FIRST_NAME       VARCHAR(255),
  LAST_NAME        VARCHAR(255),
  E_MAIL           VARCHAR(255)           NOT NULL,
  STREET           VARCHAR(255)           NOT NULL,
  ZIP_CODE         VARCHAR(255)           NOT NULL,
  CITY             VARCHAR(255)           NOT NULL,
  BILLING_STREET   VARCHAR(255)           NOT NULL,
  BILLING_ZIP_CODE VARCHAR(255)           NOT NULL,
  BILLING_CITY     VARCHAR(255)           NOT NULL
);

CREATE TABLE USER_3
(
  ID         BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255),
  LAST_NAME  VARCHAR(255),
  E_MAIL     VARCHAR(255)           NOT NULL,
  ADDRESS    VARCHAR(255)           NOT NULL
);
